### ISSUE TITLE
[Tracking]: Integrate BEIR for Evaluation 

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6554]
### Feature Description

https://github.com/beir-cellar/beir shows that, at the time of publication, BM25+sparse embedding methods outperforms other methods including dense ANN-based retrieval. Since there are complex pipelines built with llama_index, such as multi query, or query rewriting, I believe that integrating this evaluation framework can help users be more objective about the retrieval augmented pipeline they build.

Tasks:
- [x] Basic integration: https://github.com/jerryjliu/llama_index/pull/6825
- [ ] https://github.com/jerryjliu/llama_index/issues/6877
- [x] https://github.com/jerryjliu/llama_index/issues/6878
- [ ] Utilize BEIR test sets for fine-tuning.

#### Eval Methodology
1. [Cost/Efficiency/Accuracy Tradeoff](https://arxiv.org/pdf/2212.01340.pdf)

**Comment by jon-chuang** [comment]
Hello, could we reopen this issue? It tracks other issues

**Comment by logan-markewich** [comment]
Apologies, automatic closing of linked PRs/Issues 😅
