### ISSUE TITLE
[Tracking]: Domain-Specific Document Feature Augmentation

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6675]
### Feature Description

This issue tracks Domain-Specific Document Feature Augmentation.
- [ ] Codebase: https://github.com/jerryjliu/llama_index/issues/6674
- [x] Long-document optimized: https://github.com/jerryjliu/llama_index/pull/6764
- [ ] Image: https://github.com/jerryjliu/llama_index/issues/6838

Misc: 
Design Patterns
1. https://github.com/jerryjliu/llama_index/issues/6676
