### ISSUE TITLE
[Tracking]: Tracing/Callbacks

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6689]
### Feature Description

Refactor for async-compatible granular tracing
- [x] https://github.com/jerryjliu/llama_index/issues/6602
  - [ ] Possible subtasks (outdated): https://github.com/jerryjliu/llama_index/issues/6602#issuecomment-1608754763
- [ ] https://github.com/jerryjliu/llama_index/issues/6688

Additional Callbacks
- [ ] MLflow: https://github.com/jerryjliu/llama_index/issues/6617
- [ ] Arize: https://github.com/jerryjliu/llama_index/issues/6918
