### ISSUE TITLE
[Tracking]: Better support for Local Models 

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6795]
### Feature Description

It is expensive to experiment on paid APIs like OpenAI.

For cheaper development costs, let's make it easy to switch between local and API models, and generally improve local model support.

- [x] https://github.com/jerryjliu/llama_index/issues/6720
- [x] https://github.com/jerryjliu/llama_index/issues/6793
- [ ] https://github.com/jerryjliu/llama_index/issues/6692
- [x] https://github.com/jerryjliu/llama_index/issues/6797
- [ ] https://github.com/jerryjliu/llama_index/issues/6800

**Comment by jamesbraza** [comment]
@jon-chuang FYI I have added support for [LocalAI](https://localai.io/): https://github.com/run-llama/llama_index/blob/v0.8.42/llama_index/llms/localai.py#L13

There is also an issue tracking making an example for it: https://github.com/run-llama/llama_index/issues/7907
