### ISSUE TITLE
[Tracking]: Provide Cheaper / Better `embed_model`s

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6800]
### Feature Description

Refer to this article by Nils Reimers (Cohere director of ML): https://medium.com/@nils_reimers/openai-gpt-3-text-embeddings-really-a-new-state-of-the-art-in-dense-text-embeddings-6571fe3ec9d9 (Jan 2023). 

Check if the results still hold in July 2023.

Directions to investigate:
- [x] https://github.com/jerryjliu/llama_index/issues/6801
- [x] https://github.com/jerryjliu/llama_index/issues/6577
- [ ] https://github.com/jerryjliu/llama_index/issues/6802

Resources:
1. [Academic Work Showing PLAID/ColBERTv2 and Splade on the cost-accuracy frontier](https://arxiv.org/pdf/2212.01340.pdf)

**Comment by choltha** [comment]
Did anyone test if using llama.ccp embeddings from normal LLMs work? 
https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding

**Comment by daaain** [comment]
This issue might be a bit out of date? I'm super happy with this setup, it's super fast and the quality seems great:

```python
service_context = ServiceContext.from_defaults(
    llm=LlamaCPP(...),
    embed_model=HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5"),
)
index = VectorStoreIndex.from_documents(
    documents=SimpleDirectoryReader(...),
    service_context=service_context,
    show_progress=True,
)
```
